services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - spring-mysql
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.6.4-focal
    container_name: rentCarDB
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql

networks:
  spring-mysql:

volumes:
  db-data:
