services:
#  backend:
#    build: backend
#    restart: always
#    secrets:
#      - db-password
#    environment:
#      MYSQL_HOST: db
#    networks:
#      - spring-mysql
#    depends_on:
#      - db
  db:
    image: mariadb:10.6.4-focal
    environment:
      - MYSQL_DATABASE=rent_car
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-mysql: {}